### ISSUE TITLE
Only a part of the screen is drawing in full screen mode

### ISSUE THREAD

**Issue by irishgreencitrus** [mbrlabs/Lorien#1]
**Lorien version:**
v0.1.0

**OS/device including version:**
Device             Surface Pro 7
Processor	Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz   1.50 GHz
Installed RAM	8.00 GB (7.60 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Issue description:**

![image](https://user-images.githubusercontent.com/43090499/119266223-cad62680-bbe1-11eb-8736-2fe3c847588c.png)

**Steps to reproduce:**
Full screened, zoomed in and drew around as much as possible however not all the screen was drawing.

**Comment by mbrlabs** [comment]
Thanks for reporting that! I think that's because of the viewport size i use for the drawing canvas (currently hardcoded at 1920x1080) since the rest of the ui gets rendered correctly. What's your screen resolution?

**Comment by irishgreencitrus** [comment]
2736 x 1824
I'm looking for a solution to this atm and if i find one i'll submit a PR
