### ISSUE TITLE
Invisible file tree for FileDialog

### ISSUE THREAD

**Issue by Gurchain** [mbrlabs/Lorien#104]
**Lorien version:**

Lorien 5.0 dev (1e11cd7dcfad954219873de4e6e9c05de70617d5)

**OS/device including version:**

Linux (Pop OS 21.10)

**Issue description:**

FileDialog doesn't display anything when focused

**Steps to reproduce:**
Open the FileDialog and have the file tree in focus

Its because the focus style in tree for the dark theme is applied on top of the actual file tree. See https://github.com/godotengine/godot/issues/54107.

I have a fix for this and can start a pull request later.

**Comment by mbrlabs** [comment]
Yeah i noticed that as well since Godot 3.4. Thanks for figuring it out!
