### ISSUE TITLE
The eraser mark is visible in the selector tool.

### ISSUE THREAD

**Issue by EmirLogas** [mbrlabs/Lorien#106]
**Lorien version:** 0.4.0

**OS/device including version:** Windows 10

**Issue description:** The eraser mark is visible in the selector tool.

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/76751818/151041399-e3ad59cc-a40a-4f51-8995-568f54573603.png)

**Comment by EmirLogas** [comment]
https://user-images.githubusercontent.com/76751818/151041668-d07ac117-cf70-4971-96a6-6b8525d4b879.mp4

**Comment by EmirLogas** [comment]
Video: https://user-images.githubusercontent.com/76751818/151041782-8e28ea84-36eb-4882-9ffc-efd63cd37db1.mp4

**Comment by loirblitzt** [comment]
I think it is not really a bug, because the way the eraser is implemented is as a "negative brush stroke". It does not modify the vertex of an other stroke. Therefore it is selectionnable and translatable as any other stroke.

**Comment by mbrlabs** [comment]
@loirblitzt is right.

I'm not sure if i want to keep it like that though. For 1.0 i might complety replace this with the supereraser idea in #74. Anyway, closing this since this is the indented behaviour for now.
