### ISSUE TITLE
Replay a whiteboard session from saved history and timing data

### ISSUE THREAD

**Issue by lparth** [mbrlabs/Lorien#109]
**Feature/enhancement description:**

Wondering if timing information can be added to the saved history, could we then build a replay of the whiteboard session? Something in the lines of script/scriptreplay of a terminal session. This could be very useful to create videos during post-production instead of needing to screenrecord the whiteboard session.

**Comment by mbrlabs** [comment]
Closing this because it's out of the scope of this program. Neat idea though ;)
