### ISSUE TITLE
Color Presets don't save after 1

### ISSUE THREAD

**Issue by kaiiboraka** [mbrlabs/Lorien#11]
**Lorien version:**

Lorien  v0.2.0

**OS/device including version:** 

Windows 10 Pro Version 1909

**Issue description:**

 In the Color Preset menu (top right), selecting a new color and clicking the plus button closes that color window instead of adding a new color 99% of the time. It works eventually if there are no other saved colors, but once there's at least one color saved no more will save, and enough attempts at adding another causes the program to eventually crash.

**Steps to reproduce:**

Example demonstration.
https://gyazo.com/ea22705f1ef3c8c12d98a1565d55542e

I was able to get that ^ previous color to save eventually, but it proceeded to not save further colors.
![image](https://user-images.githubusercontent.com/7596816/120709701-6dac6180-c47a-11eb-8176-6f6d7dd813ab.png)

**Comment by mbrlabs** [comment]
Thanks for reporting that! The color preset option in the color pickers are part of the widget provided by Godot. But i have not hooked those up yet, so it's expected that it is not working right now.
 
I'm not sure if i'm going to keep those in the future though. I might disable them and implement my own pallete/preset system.

**Comment by mbrlabs** [comment]
I removed the presets from all color pickers in 55dfedc0601626156c10df2af52f05872b098c6d. Like i said, i'm going to implement color palettes and presets myself with a custom UI in the future.
