### ISSUE TITLE
Several Keybinds Not Working on MacOS

### ISSUE THREAD

**Issue by UdderNonsense** [mbrlabs/Lorien#114]
**Lorien version:**

v0.4.0

**OS/device including version:**

macOS Monterery 12.2.1
MacBook Air M1 2020

**Issue description:**

I tried to use the given key binds on the laptop's own keyboard that I learned from 
https://github.com/mbrlabs/Lorien/blob/main/docs/manuals/manual_v0.4.0.md
...but several of them do not work. Clicking the buttons in the UI still works.

The following keybinds do not appear to do anything:
Ctrl + S: Saves the current file
Ctrl + N: Open a new file
Ctrl + O: Open a new empty tab
Ctrl + Z: Undo a brush stroke
Ctrl + Y: Redo a brush stroke
Ctrl + C: Copy selected brush strokes
Ctrl + V: Paste copied brush strokes
Ctrl + D: Duplicate selected brush strokes

I tried this on both an external keyboard (a full Logitech Windows keyboard) and the laptop's own keyboard.

After Ctrl/control didn't work I tried using the command key instead, also to no avail.

Also, I can not do scroll actions using two finger touch on the track pad; I do not know if this is actually a bug, but it would be nice to see changed, as well as other track pad gestures.

**Steps to reproduce:**
I opened Lorien after making sure to download a new copy of the app. I unplugged all external keyboards/drawing pads. I then tried all of the keybinds until I either saw something expected happen, or gave up. I then did the same using the command key, instead of the control key, for each key bind (as appropriate).

**Comment by UdderNonsense** [comment]
Edit: added "Also, I can not do scroll actions using two finger touch on the track pad; I do not know if this is actually a bug, but it would be nice to see changed, as well as other track pad gestures." to **Issue Description**.

**Comment by mbrlabs** [comment]
Hello, yeah i noticed that as well when i last tried it on an Apple device. I think it works when you press `CTRL + COMMAND + KEY`.
I think it's something related to Godot. Not sure if that behaviour can be overridden to use the `COMMAND` key only. ...I think that's the standard way to do something like that on macos, but i'am not sure.

**Comment by mbrlabs** [comment]
Fixed in https://github.com/mbrlabs/Lorien/issues/114
