### ISSUE TITLE
Support erasing from pen's button

### ISSUE THREAD

**Issue by ZvikaZ** [mbrlabs/Lorien#118]
**Feature/enhancement description:**

Hi.
Your program looks great. However, I'm using it with Wacom Intuos, which has the ability to configure one of the pen's button as "eraser". Other applications, such as Microsoft Whiteboard, respect this. But with Lorien it's just ignored.

I see here two possible solutions:
- support the button's API
- or maybe, even as a temporary bypass for this problem, make a "temporary erasing mode", maybe by clicking `SHIFT` or some other modifier key; and then we can map the pen's button to that modifier key. 

I'm aware of the `E` shortcut to enable erasing mode, but this can't be used, because the it won't came back to brush mode when the button is released

**Comment by mbrlabs** [comment]
Unfortunally i don't think there is a way to do this in Godot as of now. The "temporary erasing mode" sounds like a good idea, but the shift modifier is already used for various other tools (like snapping in the line tool for example), so that would have to be a different key.

**Comment by ZvikaZ** [comment]
Well, shift was just an example. It can be any modifier.

**Comment by davidpanic** [comment]
This is the only feature missing that's preventing me from using lorien. I have gotten so used to being able to hold that button to erase that I press it with muscle memory and in lorien it just draws strokes instead of erasing. This completely ruins the experience for me.

**Comment by 0xNF** [comment]
How about getting this to work with the [Surface Slim Pen 2](https://www.microsoft.com/en-us/d/surface-slim-pen-2/8tb9xw8rwc14?activetab=pivot:overviewtab)? Other drawing applications, especially One Note, permit using the reverse end of the pen as an eraser.

**Comment by hansemro** [comment]
I am working on adding this feature to godot engine. So far, managed to get Linux and Windows support (winink driver only).

Project status: https://github.com/hansemro/godot/discussions/1

**Comment by hansemro** [comment]
Added wintab support.

**Comment by hansemro** [comment]
Experimental Lorien tree: https://github.com/hansemro/Lorien/tree/eraser-detect-dev

Will add test builds at some point.

**Comment by hansemro** [comment]
https://user-images.githubusercontent.com/40348686/174579829-925b006c-8485-4e6c-8513-35475fce4b2a.mp4

Fixed macOS support.

**Comment by hansemro** [comment]
Added godot engine 3.5.rc/3.x builds for anyone interested in testing experimental branch: https://github.com/hansemro/godot/releases/tag/3.5.rc-eraser-detect-r1

**Comment by hansemro** [comment]
There are some things I can cleanup but PR is ready to be reviewed as is. Also not going to rebase or squash until told to.

**Comment by hansemro** [comment]
Merged in godot master/4.rc: https://github.com/godotengine/godot/commit/6dcc9d11319ddb59089fb54551f852249081e027

Do I need to create another PR to backport it to 3.x?

**Comment by mbrlabs** [comment]
@hansemro  Yes, you have to create annother PR with a 3.x version and open it against that branch. Normally Akien can cherrypick a lot of stuff for you, but things in that area apparently changed to much between 4.0 and 3.x.

**Comment by hansemro** [comment]
Took some time, but PR for 3.x got merged: https://github.com/godotengine/godot/commit/101cbe5d5bbb6454867756152210f2b33b9877e0

Now, we wait for 3.5 stable to land...

**Comment by mbrlabs** [comment]
We got a bit lucky that it got merged so close to release😁, so good work and thanks a lot!

**Comment by davidpanic** [comment]
[3.5 stable](https://github.com/godotengine/godot/releases/tag/3.5-stable) has landed :tada:, are there any plans on this being merged and released soon?

**Comment by hansemro** [comment]
I'll leave it to @mbrlabs to implement the feature more sanely.

**Comment by mbrlabs** [comment]
I'm looking into it :)

**Comment by mbrlabs** [comment]
Implemented in https://github.com/mbrlabs/Lorien/pull/225
