### ISSUE TITLE
Brush strokes not placed correctly with custom UI scale

### ISSUE THREAD

**Issue by hansemro** [mbrlabs/Lorien#129]
**Lorien version: v0.5.0-dev**
Regression introduced by 336ba416a3e198469863caed7be6dc7f2262d513

**OS/device including version:**
Arch Linux
Windows 10
macOS 11.6.5

**Issue description:**
When using a custom UI Scale setting, brush strokes are placed at an offset from the cursor. Issue is not present when UI Scale is set to 1.

**Steps to reproduce:**
Set UI Scale to a value greater than 1 and draw with the brush tool.

**Comment by mbrlabs** [comment]
Good catch, thanks for reporting.
