### ISSUE TITLE
Windows Icon Scaling

### ISSUE THREAD

**Issue by zonfr** [mbrlabs/Lorien#139]
**Feature/enhancement description:**
In the File explorer, when I'm in Small icon mode, the icon of Lorien is in good resolution but when I switch to Medium or Large icon mode, it become pixelated.
![image](https://user-images.githubusercontent.com/38401883/173341428-77ef0358-17c9-47a4-9c13-6339505ea902.png)
![image](https://user-images.githubusercontent.com/38401883/173341468-02539a1e-1be1-4959-999e-1f1a350019c8.png)

**Comment by mbrlabs** [comment]
Fixed in #265
