### ISSUE TITLE
Add alternative hotkey for panning the view

### ISSUE THREAD

**Issue by popcar2** [mbrlabs/Lorien#147]
**Feature/enhancement description:**
Right now the only way you can pan the camera is with the middle mouse button. There doesn't seem to be an alternative for people who are using touchpads (laptop).

There should be an alternative like `ctrl + left mouse` or `shift + left mouse` for people with faulty middle mouse buttons or no mouse.

**Comment by mbrlabs** [comment]
Are you using a drawing tablet? If so you can map the middle mouse button to one of the pen's keys. That's how i pan with a tablet.

But i agree that there should be some kind of fallback mechanism.

**Comment by popcar2** [comment]
I use a mouse mainly, but when my mouse wasn't next to me I used my touchpad a little bit and was surprised there isn't a different way to pan

**Comment by mbrlabs** [comment]
Implemented in #278
