### ISSUE TITLE
Segmentation fault when switching modes mid-stroke

### ISSUE THREAD

**Issue by sigaloid** [mbrlabs/Lorien#153]
**Lorien version:**
0.5.0

**OS/device including version:**
Fedora 35

**Issue description:**
Drawing on my tablet (using OpenTabletDriver), and it crashed. 

**Steps to reproduce:**
1. Be using tablet with OpenTabletDriver
2. Press eraser hotkey mid-pen-stroke
3. Release pen
4. Re-touch pen to tablet, and SIGSEGV occurs

https://user-images.githubusercontent.com/69441971/173972831-3d5941f9-2a77-490c-a230-ecc0dccb0b2f.mp4

**Comment by hansemro** [comment]
Looks like this occured because end_stroke() did not get invoked in BrushTool.gd:_input before switching tools. Issue also does not require tablet to replicate.

**Comment by hansemro** [comment]
Same issue occurs for rectangle, circle, and line tools.

**Comment by sigaloid** [comment]
Works on my end, thanks for the quick fix! :smile:
