### ISSUE TITLE
Blurry interface on 13" MacBook

### ISSUE THREAD

**Issue by teenjuna** [mbrlabs/Lorien#162]
Following the discussion in #4 

**Lorien version:**
v0.5.0

**OS/device including version:**
13" MacBook Pro (res. is 2560x1600) with M1 silicon 

**Issue description:**
As described in [here](https://github.com/mbrlabs/Lorien/issues/4#issuecomment-1153467722), the app interface looks pretty much blurry on my screen. For some reason, when the app is open, even the text on Mac's native menu bar is blurry. The scaling options don't solve the problem. Screenshots are provided in the linked discussion. 

**Steps to reproduce:**
Open the app on a high DPI screen I guess.

**Comment by mbrlabs** [comment]
Fixed in #164. Not sure why Github didn't close it.

**Comment by hansemro** [comment]
@mbrlabs I made the mistake of enclosing the issue # with parenthesis.

**Comment by qiaolin-li** [comment]
When will this new version be available? The current macbook 13 "experience is terrible

**Comment by mbrlabs** [comment]
@qiaolin-li i don't know yet. I'm a bit busy currently, so it's probably going to take a while. I also want to get in some more features.
