### ISSUE TITLE
Adding a presentation mode

### ISSUE THREAD

**Issue by Variable-ind** [mbrlabs/Lorien#181]
**Feature/enhancement description:**

Hy, i loved this software, i just need another feature that another similar godot whiteboard app has which is presentation mode 

https://user-images.githubusercontent.com/77773850/178216154-802a9fca-6b6e-4110-b819-f868beab1a1a.mp4

**Comment by mbrlabs** [comment]
Interesting idea, but i don't think that's something i want in Lorien. Seems too niche and not fit for a drawing/whiteboard app like this. If you want to make a presentation, use a presentation-making software ;)
