### ISSUE TITLE
Lorien not working when installed through snap.

### ISSUE THREAD

**Issue by fhvirus** [mbrlabs/Lorien#182]
I'm using Ubuntu 22.04, and I tried to install Lorien 0.5.0 through snap. However, when I clicked the icon in the Applications, nothing happens. But when I run the executable downloaded from the release page, it works normally.

**Comment by mbrlabs** [comment]
You have to talk to @tonybolzan about that. I don't maintain that package.
This is the repo: https://github.com/tonybolzan/snap-lorien. I suggest you open an issue there

**Comment by tonybolzan** [comment]
@fhvirus Open a issue with more information about the problem in [my repo](https://github.com/tonybolzan/snap-lorien/issues).
And try running Lorien from terminal.
```sh
snap run lorien
```
