### ISSUE TITLE
assets file sometimes are missing the v char.

### ISSUE THREAD

**Issue by 5cat** [mbrlabs/Lorien#184]
**Feature/enhancement description:**

In the release section https://github.com/mbrlabs/Lorien/releases sometimes the asset files have a `v` next to the version and sometimes it is not.
It would make it easier for package managers to automatically pump the version without worrying if the `v` exist in this release or not.
May I ask if it would be possible to add `Lorien_v0.5.0_Linux.tar.xz` along side the `Lorien_0.5.0_Linux.tar.xz` file in the release?

Thank you,

**Comment by mbrlabs** [comment]
Oops my bad, sorry! I don't want to upload an identical version just for the additional `v` though...becomes a bit confusing for users when there are two versions online with no apparent difference. And replacing it would break people's already existing setups.

So i promise to keep the `Lorien_vX.Y.Z_Linux.tar.xz` format in the next release ;)
