### ISSUE TITLE
Selection rectangle stays if right click pressed without letting go of left click

### ISSUE THREAD

**Issue by Astrono2** [mbrlabs/Lorien#19]
**Lorien version:** 0.2.0

**OS/device including version:**
Operating System: Arch Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.9-arch1-1
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Issue description:**
When holding left click to drag a rectangle with the selection tool, if right click is pressed the selection is cancelled. The expected behavior in this case would be for the selection box to disappear, but it remains in it's last state before the selection was cancelled until another selection is started.

**Steps to reproduce:**
Start dragging a selection rectangle and, without letting go of left click, press right click.

**Comment by mbrlabs** [comment]
Thanks for reporting that. I fixed it.
