### ISSUE TITLE
Single-handed tool hotkeys

### ISSUE THREAD

**Issue by lparth** [mbrlabs/Lorien#191]
**Feature/enhancement description:**

From an ergonomic and user perspective, single-handed tool hotkeys are very efficient. I'm a right-hander and I'd like hold the pen on the right hand and use the left-hand on the keyboard. So, I had to remap just the Line tool (L) to (A) and I was done. However, a left-hander would need to remap 5 out of the 6 keys.

I think it would be nice to have a global configuration option called single-handed tool hotkeys and provide the two mappings plus the current mapping as a third and default because of its explicit link to the tool name. Let me know what you think.

Thanks
~parthi

**Comment by mbrlabs** [comment]
In the main latest main branch @MrApplejuice implemented a way to rebind any keyboard shortcut to anything you want (you can also have multiple key combos bound to one action). I guess that would solve this issue and is a more general solution to the problem your'e having.

See: https://github.com/mbrlabs/Lorien/pull/169

**Comment by lparth** [comment]
Thanks @mbrlabs , I'll check it out.

**Comment by mbrlabs** [comment]
Alrght, closing this then :)
