### ISSUE TITLE
Canvas color not set

### ISSUE THREAD

**Issue by nithinshoban** [mbrlabs/Lorien#193]
**Lorien version:**

lorien V 0.5.0

**OS/device including version:**

Windows 11

**Issue description:**

1.Open a new tab
2.Set different canvas color in new tab
3.Move to another tab 
4.Return back to new tab
5.Canvas color is not reflected or not set
I would expect that canvas color to show previously set colour

**Steps to reproduce:**
Described in previous section

**Comment by mbrlabs** [comment]
Fixed in b7b649995f35cb89375460215ac19b7ffb13a27d. This only affected unsaved files.
