### ISSUE TITLE
Grid Size: ability for user to change

### ISSUE THREAD

**Issue by johnblat64** [mbrlabs/Lorien#197]
- Allow user to set default grid size in settings
- Allow user to set current grid size using a new slider on the toolbar

**Comment by johnblat64** [comment]
I'm going to work on this. I'll submit it when done and it see if it is good.

**Comment by mbrlabs** [comment]
Good idea, but this should't be t be in the toolbar. It's reserved for tools which you use regularly and i think you do that maybe once or twice with the grid size (if at all) and then you are done.

**Comment by johnblat64** [comment]
@mbrlabs 
Should it go in only the settings dialogue then?

**Comment by mbrlabs** [comment]
Yes ;)

**Comment by johnblat64** [comment]
What tab should this setting go under?

**Comment by mbrlabs** [comment]
Appearance would be good i think

**Comment by johnblat64** [comment]
@mbrlabs should there be a `default_grid_size` setting or a `grid_size` setting, or both?

**Comment by mbrlabs** [comment]
Not sure what you mean by that. To start i suggest to just add one gird size setting to the settings dialog and don't save it in the actual file at all. So it's purely visual. After that i planned to implement different grid types (see the linked issue in the comment above). Then we can maybe think about putting grid size info into the save file.

**Comment by mbrlabs** [comment]
Implemented in #199
