### ISSUE TITLE
Add HandWriting and Draw detection

### ISSUE THREAD

**Issue by Endergamer200111** [mbrlabs/Lorien#201]
Adding the detection of handwriting and drawings would make it possible to select and correct them, for example if you make a circle by hand you can make it perfectly round. And if you write with your hand, you can transform it into a text in a pre-selected font. 

![circle](https://user-images.githubusercontent.com/59482743/188290133-1eefc0f0-c0af-482d-9b28-263478954cf8.png)
![text corrected](https://user-images.githubusercontent.com/59482743/188290132-a4a12ac6-8aeb-436f-a7d1-80f01d95ac9f.png)

**Comment by mbrlabs** [comment]
That's out of the scope of the project, sorry.
