### ISSUE TITLE
Moved strokes stay in their original positions after exporting

### ISSUE THREAD

**Issue by ghost** [mbrlabs/Lorien#210]
**Lorien version:** Tried both on 0.5.0 and b5aee8c

**OS/device including version:** Both Windows 10 (0.5.0 and b5aee8c) and Linux (just 0.5.0, haven't checked b5aee8c)

**Issue description:**
Using the selection tool on strokes to move them does not move them relative to other strokes upon svg export, they move only in the application. I am not sure if this is intended behavior or a bug, it does not really seem like sensible behavior to me. If there is any information I missed, I will try to provide it.

**Steps to reproduce:**
1. Draw 2 strokes.
2. Note their relative positions
3. Move one of them with the selection tool.
4. Export as svg.
5. Notice that the move tool had no effect on the exported project, the moved stroke is still in its initial position relative to the other one.

**Comment by droshux** [comment]
I am currently experiencing this bug  on lorien-bin 0.5.0-1 (installed from the AUR).
