### ISSUE TITLE
--no-save option

### ISSUE THREAD

**Issue by LoganDungeon** [mbrlabs/Lorien#211]
**Feature/enhancement description:**
I think a simple feature that can be quite useful would be a `--no-save` option. 
To start Lorien, scribble something and then close it again, without getting asked if i want to save it.

Maybe this could be implemented together with the option of autosaves as described in #174.

**Comment by mbrlabs** [comment]
While relatively easy to implement i don't think this is a very useful feature. Sorry, closing.
