### ISSUE TITLE
The brush size is not equal to other tools size

### ISSUE THREAD

**Issue by mshahedi83** [mbrlabs/Lorien#216]
**Lorien version:**
Lorien  0.5.0 Linux

**OS/device including version:**
OS: Linux Ubuntu 18.04.6
GPU: NVIDIA GeForce 920MX
GPU Driver: NVIDIA Driver metapackage from nvidia-driver-470 (proprietary, tested) installed from the "Software & Updates" of Ubuntu

**Issue description:**
Hello, i'm using Linux Ubuntu 18.04.6 and i downloaded Lorien 0.5.0 from github
excuse me ,first of all, scale ui is not appropriate in auto mode that fix after changes to custom and 1.
but The brush size is not equal to other tools size, that's meaning with equal size The brush size is Thicker than other tools size.

and when i insert a Rectangle the vertex from which the Rectangle is drawn, seem's hasn't anti-aliasing.

please pay attention to [this video](https://drive.google.com/file/d/1CBl-sOJktmFSATZwrVt2bk19GxbhKk-V/view?usp=drivesdk).

**Steps to reproduce:**
1. Set brush size for Drawing
2. Draw with the brush tool
3. Draw with other tools when the brush size hasn't changed

**Comment by mshahedi83** [comment]
Hello, sorry, This problem happens only when the mouse is connected (the pen tablet didn't connected), and the problem didn't happens, when the pen tablet is connected.

**Comment by mbrlabs** [comment]
Fixed with #263
