### ISSUE TITLE
Some features for notemaking

### ISSUE THREAD

**Issue by nitin-fern** [mbrlabs/Lorien#219]
**Feature/enhancement Description:**

This is an impressive note-making app. So I would like to thank all the contributors for their efforts in building this application.

I would like to point out a missing feature that will be helpful for most users who use this software for note-making.

> Currently there is **no option to scroll across the infinite canvas at a fixed zoom level**. To move downwards one has to first zoom in at some bottom point and then zoom out at some top point. I request the contributors to add this feature so that one can move across the canvas easily.

> Unlike drawing, note-making does not need a canvas that is infinitely sized horizontally. One direction is often sufficient. **Maybe we can have a note-making mode when the canvas extends to infinity only in the vertical direction.**

> It would be helpful if we have more than one canvas in a file for easy organization of topics.

**Comment by mbrlabs** [comment]
1. Not sure if i understand you correctly. You can pan across the canvas using the middle mouse button.
2. No, i don't want to add a vertical only mode. If you don't need the horizontal space just don't use it ;)
3. I get what you mean, but that kinda goes against the keep it simple philosophy of this app. It's also why i don't want to add layers. Just use multiple files.
