### ISSUE TITLE
Adding key binds for all the tools

### ISSUE THREAD

**Issue by CrownedMt** [mbrlabs/Lorien#235]
Adding a key bind that switches the tool to the next desired one will be very convenient especially undo and redo key binds. 

Such as:
Undo - ctrl z
Redo - ctrl shift z
Brush- b
Eraser - e

**Comment by tokazio** [comment]
save - ctrl+s

**Comment by mbrlabs** [comment]
Shortcuts have been implemented since the first public release. See the manual: https://github.com/mbrlabs/Lorien/blob/main/docs/manuals/manual_v0.6.0.md
