### ISSUE TITLE
Win 10 Open with... support

### ISSUE THREAD

**Issue by niposch** [mbrlabs/Lorien#24]
**Feature/enhancement description:**

I am double clicking on a .lorien file in windows explorer. It opens  the "open with" dialog and I select lorien.exe.
When I try to open the .lorien file it should open the file in lorien. It instead opens a new untitled file in a new window of lorien. 

I am running windows 10 pro 21h1

The program should be able to open a supported file by selecting the lorien.exe in the "open with..." dialog.

**Comment by mbrlabs** [comment]
Good idea! I did some research and it's possible to do that. But unfortunally it's always going to open a new instance of Lorien and it's currently not possible to open the file in a new tab if Lorien is already running (would probably require some Windows specifc stuff or inter process communication...not sure). 

It's still better than nothing, so i'm going to implement it. I'm also going to add the ability to drag and drop files from the Windows Explorer into the running program to open them.
