### ISSUE TITLE
Lorien Not Launching After Snap Installation on Fedora 37

### ISSUE THREAD

**Issue by AlbertSolomon** [mbrlabs/Lorien#247]
**Issue:**
Lorien, an application installed via Snap on Fedora 37, is not launching as expected.

**Details:**
I successfully installed **Lorien v0.5.0** using the Snap package manager on my Fedora 37 system. However, I am encountering an issue where the application fails to launch. Despite the installation process completing without errors, attempting to run Lorien doesn't yield any results.

**Steps Taken:**

Installed Lorien using the Snap package manager.
Tried launching Lorien from the command line and application menu.

**Expected Behavior:**
Lorien should launch and be accessible after installation via Snap.

**Actual Behavior:**
Lorien is not launching, rendering it inaccessible for use.

**System Information:**
**_Operating System: Fedora 37_**
Installation Method: Snap package manager
This issue is hindering my ability to use Lorien for its intended purpose. Any guidance or assistance to resolve this problem would be greatly appreciated.

**Comment by mbrlabs** [comment]
I don't maintain that package. Can you check if Lorien works by downloading it from [Github](https://github.com/mbrlabs/Lorien/releases) instead? Feel free to open this again when it still does not work.
