### ISSUE TITLE
Cursor not showing in "Save changes?" dialog when closing the app

### ISSUE THREAD

**Issue by GeertJohan** [mbrlabs/Lorien#253]
**Lorien version:** 0.6.0 release from github for Linux

**OS/device including version:** Linux Ubuntu 22.04.3 LTS with X11, LightDM (display manager) and xmonad (window manager). Nvidia graphics drivers.

**Issue description:** The cursor disappears over the "Save changes?" when closing the application.
In other dialogs (save file) I get my default system cursor (the dark mode variant, which is nice).

**Steps to reproduce:**
Exit, then hover mouse over the "Save changes?" dialog.

**Comment by mbrlabs** [comment]
This should be fixed now in the latest main branch. I reworked how the canvas grabs the focus of the mouse cursor.
