### ISSUE TITLE
Add another extra type of eraser

### ISSUE THREAD

**Issue by seityaya** [mbrlabs/Lorien#254]
Add another type of eraser that doesn't erase everything completely, but only partially. Some part of a written or drawn figure.

**Comment by mbrlabs** [comment]
The original eraser worked like that, but the design of the app lends itself better to the current eraser. Another type of eraser would just be confusing, so closing this.

**Comment by andrewbaxter** [comment]
What about the design of the app lends itself better to the current eraser?
