### ISSUE TITLE
Can't ge tthe Simulated pressure effect with the new version

### ISSUE THREAD

**Issue by MotherSoraka** [mbrlabs/Lorien#267]
![image](https://github.com/mbrlabs/Lorien/assets/72297825/84d6d45d-c36a-401e-9c1a-ca6db909fa0f)

both were done with mouse
Left is 0.2.0
Right is 0.6.0

what happened?

**Comment by mbrlabs** [comment]
Your default pressure is probably too high. Try lowering your pressure sensitivity in the settings.

**Comment by toboil-features** [comment]
Can confirm with default settings on 0.7.0-dev.

**Comment by mbrlabs** [comment]
Something like this was never intended, so this was a bug in v0.2. However i just implemented velocity based line thickness in 3dd930b56f314beda9bbcf151834fe9e73403efb which does something similar.
