### ISSUE TITLE
Idea: better color picker

### ISSUE THREAD

**Issue by nm17** [mbrlabs/Lorien#27]
**Feature/enhancement description:**
Currently, our color picker is great, but not good for quickly changing commonly used colors:
![image](https://user-images.githubusercontent.com/23419131/122051713-f8377e00-cdf5-11eb-8b1f-59c253ce2c55.png)

Inkscape has an amazing color picker and I think Lorien could really benefit from implementing something like this:
![image](https://user-images.githubusercontent.com/23419131/122050971-1e105300-cdf5-11eb-8091-254c16266d28.png)

While it's not necessary to do it exactly like that, the colors themselves and the idea of putting commonly used colors somewhere easy to access is a really great thing to have.

**Comment by mbrlabs** [comment]
That's actually exactly what i want to do and why i removed the color presets from Godot's colorpicker. But i'm not sure about the UI yet. I want to implement a system where you can define colors palettes yourself and also have a default one with some nice colors similar to Inkscape (but with less colors).

**Comment by Gurchain** [comment]
How about something like this:

![ColorPallete1](https://user-images.githubusercontent.com/89324754/130339486-b622840c-e17b-47cd-b19d-97ff3afd9e9e.png)
![ColorPallete2](https://user-images.githubusercontent.com/89324754/130339490-60949c5e-1580-4d3d-912b-c657af05bbdd.png)

**Comment by mbrlabs** [comment]
@Gurchain Yes good idea, that's how i want to do it esentially (very Paint inspired). But i'm unsure if i want to limit the amount of slots you can have (you can't show all of them in the toolbar). It's probably fine to have a fixed nubmer, since you don't need so many anyway. But you should be able to edit them or create new color palettes yourself.

**Comment by Gurchain** [comment]
Maybe you have one row of colours show in the toolbar and you can click a drop-down menu to show a couple more rows, including an option to swap palettes.

**Comment by mbrlabs** [comment]
See https://github.com/mbrlabs/Lorien/pull/55#issuecomment-916839551

**Comment by mbrlabs** [comment]
I'm working on a new color picker. Right now it's all static (you can't change colors). But in the future you will be able to change them, add new palettes yourself, etc.

This is how it looks like so far:
https://user-images.githubusercontent.com/8750135/132878544-67f977c1-2126-40f9-8ce0-7d48e94c0134.mp4
