### ISSUE TITLE
Adding Text Box & Fixing Fullscreen Bug 

### ISSUE THREAD

**Issue by brightuniverse** [mbrlabs/Lorien#274]
Hi Support Team,
I really appreciate your effort!

However, I was wondering if we could add text boxes as well.
Also, when the app is Fullscreen on Windows, we can't close it. 

Please let me know what you think
Thank you so much

**Comment by mbrlabs** [comment]
Duplicate of #274

Eventually we'll add it :)

**Comment by valeratrades** [comment]
I've been searching all over for a simple straightforward whiteboard app, and Lorien seems to be perfect on all axis except this one.

Can't use the app without keyboard text input, so willing to attempt contributing if you greenlight the feature.
