### ISSUE TITLE
Ctrl + Q doesn't work

### ISSUE THREAD

**Issue by toboil-features** [mbrlabs/Lorien#282]
**Feature/enhancement description:**
Lorien could be closed by Ctrl + Q shortcut, habit in this case will not be interrupted.
Currently i can't use the function nor can bind it in the shortcuts menu. I use Lorien 0.6.0.
![Lorien](https://github.com/mbrlabs/Lorien/assets/160222185/fff2ccbc-dcb1-47fe-988c-7eabe09298a8)

**Comment by mbrlabs** [comment]
Implemented in https://github.com/mbrlabs/Lorien/commit/1f656406dc3c0e90319c110cc0b827c3403fd3a7

**Comment by toboil-features** [comment]
I want to add one more thing...
When I try to close empty default canvas with Ctrl+Q, it shows unnecessary window with attempt to save it. I think this window is kinda useless.
![Showcase](https://github.com/user-attachments/assets/957544e8-2b1f-4c01-a1b2-2bee2f5bd326)
