### ISSUE TITLE
Allow user to set TARGET_FPS_FOREGROUND & TARGET_FPS_BACKGROUND

### ISSUE THREAD

**Issue by Allstreamer** [mbrlabs/Lorien#29]
**Feature/enhancement description:**
I would love the option to set these two values:
TARGET_FPS_FOREGROUND
TARGET_FPS_BACKGROUND

**Comment by mbrlabs** [comment]
Yeah good idea. I'm a bit busy at the moment, but this seems like a good feature for a first pull request if you want to tackle it ;)

**Comment by Allstreamer** [comment]
Yeah, I'd love to contribute!
I'll look into it

**Comment by mbrlabs** [comment]
Implemented in #32
