### ISSUE TITLE
Quality of Life shortcuts

### ISSUE THREAD

**Issue by toboil-features** [mbrlabs/Lorien#295]
**Feature/enhancement description:**
I want to see shortcuts below to be implemented, because they speed up interaction with program:
- Ctrl+PageUp - To move to previous file.
- Ctrl+PageDown - To move to next file.
- Ctrl+W - To close current file.
- Ctrl+Shift+T - To restore closed file.

These ones were not been mentioned before.

**Comment by mbrlabs** [comment]
I implemented the CTRL+W shortcut the close the current file: 8c9a3ff2e1e4b5e5f5122b1e9ba1e5fa490a716f. The other shortcuts don't seem very useful/common so i'd rather not implement them.

**Comment by toboil-features** [comment]
They are useful and even integrated in browsers. Three of those you left behind are integrated in Firefox at least.
