### ISSUE TITLE
Lorien is constantly playing sound

### ISSUE THREAD

**Issue by toboil-features** [mbrlabs/Lorien#297]
**Lorien version:**
0.6.0, 0.7.0-dev

**OS/device including version:**
Operating System: Arch Linux
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.7-arch1-1 (64-bit)
Graphics Platform: Wayland

**Issue description:**
![Showcase](https://github.com/user-attachments/assets/0902566c-c54d-4f83-b9d1-24da3525f3c5)

**Steps to reproduce:**
1. Start the app.

**Comment by Zireael07** [comment]
That's a Godot bug, not a Lorien bug

**Comment by mbrlabs** [comment]
I think you set the audio driver in Godot to a dummy implementation, so that all audio features get functionally disabled. I don't know if that fixes this issue, but i'm looking into it.

**Comment by mbrlabs** [comment]
@toboil-features Could you try the lastest main branch. Should be fixed now.

**Comment by toboil-features** [comment]
@mbrlabs Yes, now it is fixed.
