### ISSUE TITLE
Changing Color on Selction Tool active crashes App

### ISSUE THREAD

**Issue by raumkauz** [mbrlabs/Lorien#298]
I couldn't find anything related to this. Even though I think it's not that uncommon to do that.

**Lorien version:**
Lorien v0.7.0-dev (run viaeditor debug, no build) - I think that's the latest available version

**OS/device including version:**
Windows 10

**Issue description:**
It says:
Invalid type in function '_modify_strokes_colors' in base 'Node (SelectionTool)'. The array of argument 1 (Array[Node]) does not have the same element type as the expected typed array argument.

**Steps to reproduce:**
1. Select Selection Tool via toolbar in app
2. Change color
3. App crashes

**Comment by mbrlabs** [comment]
Thanks for the report! I just fixed it in 112ff31dea90b2cfddc085ca0be866ccb173f8b2.
