### ISSUE TITLE
Character from F12 is pixelated if zooming too close

### ISSUE THREAD

**Issue by toboil-features** [mbrlabs/Lorien#299]
**OS/device including version:**
Operating System: Arch Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.7-arch1-1 (64-bit)
Graphics Platform: Wayland

**Issue description:**
I think characher must be in vector format as SVG not in rasterized as now. 4K display owners will like it.

**Steps to reproduce:**
1. Draw a line
2. Move cursor above it
3. F12

![Showcase](https://github.com/user-attachments/assets/1d52439c-595b-4ea4-a276-f981ff63abb6)

**Comment by mbrlabs** [comment]
> I think characher must be in vector format as SVG not in rasterized as now

That's not possible. Godot does not have a built-in realtime SVG renderer. Imported svgs will always be rasterized before rendering.
