### ISSUE TITLE
Add export configurations to project repository

### ISSUE THREAD

**Issue by msnspk** [mbrlabs/Lorien#3]
In order to make it easier for users to build or package this project, would it be possible to add the `export.cfg` and `export_presets.cfg` files to this repository?

Godot supports exporting projects directly from the command-line using this syntax: `--export <preset> <path>`

(The `<path>` argument overrides the `export_path` option in `export_presets.cfg`)

So having those files included in the repository would allow users to clone and export the project automatically, such as through a script

**Comment by mbrlabs** [comment]
That sounds like a good idea, i'm going to add them soon.
I normally don't check in export configs, because often times they contain sensitive information, but for an open source project like this it's fine.
