### ISSUE TITLE
Fix unclean rectangles

### ISSUE THREAD

**Issue by Zacrain** [mbrlabs/Lorien#300]
**Feature/enhancement description:**

The rectangles are unclean.
What I mean by this: a line in the upper left corner always appears to be a bit too long. This becomes more apparent on greater line thicknesses and/or when zooming out.

Here is a screenshot to illustrate what I mean:
![image](https://github.com/user-attachments/assets/628d4996-1e07-4029-8cba-e32eae4cb8c4)

The upper left corner seems to be the only one which is affected by this. I imagine this has to do with how this is drawn under the hood.

Improving this would lead to clean and visually perfect rectangles. (And won't trigger OCDs 😁 )

**Comment by Zacrain** [comment]
Forgot to mention that this affects v0.6.0. The current main branch doesn't seem to have that problem.

**Comment by mbrlabs** [comment]
Yeah i don't see it either on the main branch (which the next version will be based upon). Closing this then.
