### ISSUE TITLE
Lorien color palette is inconvinient

### ISSUE THREAD

**Issue by toboil-features** [mbrlabs/Lorien#304]
The problem is you need to do 4 useless clicks to change color of your pencil. This is because you are forced to create yours palette to not to use default one.
Lorien is better to create it automatically under name "Palette 1", "Palette 2", etc. rather than I will create it manually because, just because.
![Showcase](https://github.com/user-attachments/assets/89cacbb3-6689-43e5-bb5e-9888d8a8e3ab)

**Comment by mbrlabs** [comment]
I prefer the current solution; makes things easier. It's not like you change color palettes constantly. Most users will probably never try to change this anyway.

**Comment by toboil-features** [comment]
Excuse me? Then why someone need to hassle with palette creation just to change the current color of pen, because you can't just change it directly?
