### ISSUE TITLE
Rounded off Line Endings Option/Default

### ISSUE THREAD

**Issue by Allstreamer** [mbrlabs/Lorien#33]
**Feature/enhancement description:**
I'd prefer the line endings shown in the image below:
![Screenshot (90)](https://user-images.githubusercontent.com/48365544/122685672-36c1a400-d20d-11eb-925d-1715e245e0e4.png)
rather than:
![Screenshot (89)](https://user-images.githubusercontent.com/48365544/122685676-3923fe00-d20d-11eb-9ceb-6b712ad6b6b0.png)

I already kind of have a solution to this, I'd like to ask though if this could just be the default or if I should make this an option in the menu.

**Comment by Allstreamer** [comment]
with this option the line would look more like drawing in a program like photoshop

(also the fact that the line is the same width in the top image is just an accident)

**Comment by mbrlabs** [comment]
I did that at first but when i switched from the OpenGL Hint Anti-Aliasing method to the Texture Fill method (for performance and compabilty reasons), these rounded caps didn't look has good...so i switched to flat ones. In your screenshots it looks fine, so i assume you enabled the OpenGL Hint method for the screenshots?

I think it's fine to add this as option under Rendering. But default should be `LINE_CAP_NONE` like right now.

**Comment by Allstreamer** [comment]
Implemented in #34
