### ISSUE TITLE
Lorien Crash when scaling window

### ISSUE THREAD

**Issue by Allstreamer** [mbrlabs/Lorien#35]
*Lorien version:*
Lorien v0.3.0-dev

Tested on Code from Commit:
09cea891b17858190b4ea3167ceede59d7c781c9

**OS/device including version:**
Windows 10 x64 | v10.0.19042 Build 19042

**Issue description:**
Lorien Crashes When scaling window as small as possible
![Screenshot (93)](https://user-images.githubusercontent.com/48365544/122990482-458e8f00-d3a4-11eb-8517-a864109dc574.png)

`
ERROR: get: FATAL: Index p_index = 1 is out of bounds (size() = 1).
   At: ./core/cowdata.h:156
`

**Steps to reproduce:**
Scale the window as small as it can go. It will hang for a few seconds then crash

**Comment by Allstreamer** [comment]
I'm working on figuring out why it crashes, but so far no luck. 
(Mainly because this is the first time I've worked with godot)

**Comment by Allstreamer** [comment]
Tested it in a new empty game just to make sure it isn't a godot problem nope it's specific to Lorien.

**Comment by Allstreamer** [comment]
So I found some code that if it's removed it stops the crash
[Here is the line in the code base](https://github.com/mbrlabs/Lorien/blob/09cea891b17858190b4ea3167ceede59d7c781c9/lorien/InfiniteCanvas/InfiniteCanvas.gd#L288)

It was added in Commit:
560131183a731f1e9020b584660b8b102eca6891

I can't find the reason why this was added, but removing it fixes the crash.

**Comment by Allstreamer** [comment]
Found out that if the resulution goes to Y <= 4 it crashes

**Comment by mbrlabs** [comment]
Thanks for figuring that out. I guess there is a lower limit to how small framebuffers can be in Godot (might be platform dependent).

**Comment by Allstreamer** [comment]
Fixed in #36
