### ISSUE TITLE
Adjustable pressure sensitivity

### ISSUE THREAD

**Issue by bennyschirm** [mbrlabs/Lorien#37]
Hello,
i am using Lorien as a Paint replacement to quickly design new levels for my game with my drawing tablet. Thank you for developing it and making it open source....i really love it! I didn't even know Godot could do that. 

I was just wondering if it is possible to add adjustable pressure because i need to press pretty hard on my tablet. Thanks

**Comment by mbrlabs** [comment]
Thank you, i'm glad you find it useful. I actually developed it for exactly that reason 😁
Sure, i think it's probably enough to add that as an option to the settings dialog.

**Comment by bennyschirm** [comment]
Awesome! yes, that is totally fine. I am just going through the code to fix annother issue. After that i can maybe try to implement this if you don't mind.

**Comment by bennyschirm** [comment]
Sorry, i closed it by accident.

**Comment by mbrlabs** [comment]
> After that i can maybe try to implement this if you don't mind.

Sure, go ahead ;)
