### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by bennyschirm** [mbrlabs/Lorien#38]
**Lorien version:**
0.2

**OS/device including version:**
Manjaro Linux

**Issue description:**
When switching to Spanish in the settings the UI gets smaller. I think i know how to fix it but i'm still struggeling a bit with Github/Git. I am going to upload a fix if i figured it out though.

![esp](https://user-images.githubusercontent.com/86534619/123524895-78e75b80-d6cd-11eb-8e3f-5b9ae266e665.png)

**Steps to reproduce:**
Change language to spanish

**Comment by mbrlabs** [comment]
Yeah, i didn't really check all the UI elements when people added new languages. Cool, if you have any questions just ask me or open a [discussion here](https://github.com/mbrlabs/Lorien/discussions).

**Comment by mbrlabs** [comment]
Fixed in #39
