### ISSUE TITLE
Improve macOS installer

### ISSUE THREAD

**Issue by haudraufhaun** [mbrlabs/Lorien#43]
I like that you provide a .dmg for installing Lorien to macOS, but it would be even better if there would be the typical 'drag the application to the applications folder'-experience.

**Comment by mbrlabs** [comment]
I can't test this right now as i don't have acccess to my Mac currently. Next time i make a release i try to see what i can do, but i'm afraid there is not much that can be customized in that regard.

**Comment by HAUDRAUFHAUN** [comment]
I could help you out if you want...

**Comment by mbrlabs** [comment]
Yeah sure, help is always welcome :)

**Comment by mbrlabs** [comment]
Closing this, because i don't think this is supported by Godot.
