### ISSUE TITLE
Changing Background color doesn't work

### ISSUE THREAD

**Issue by protodrew** [mbrlabs/Lorien#45]
When you go into settings and attempt to change the default background color. It does not affect opening on a fresh file or any previous files. Brush color does change, however, so that is functional.

**Comment by mbrlabs** [comment]
This has already been reported in https://github.com/mbrlabs/Lorien/issues/41 and was fixed in https://github.com/mbrlabs/Lorien/pull/42. The next relese will have that fix included.
