### ISSUE TITLE
Player can stand on erase paths

### ISSUE THREAD

**Issue by Astrono2** [mbrlabs/Lorien#49]
**Lorien version:**

Latest commit on player branch

**OS/device including version:**

Operating System: Arch Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.8-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Issue description:**

When the player is spawned, they have collision with both draw and erase paths, which looks unnatural.

https://user-images.githubusercontent.com/8162008/128640511-671b0e0a-6dec-4535-a2bf-1e1aa070c524.mp4

**Steps to reproduce:**
Draw with the eraser.
Spawn player and move them to where you have drawn with the eraser.

**Comment by Astrono2** [comment]
I know this is dumb lol but being able to erase the ground would be pretty neat

**Comment by mbrlabs** [comment]
I know 😄. Unfortunally none of the tools were desinged to interact with a player in a platformer game. I was actually really surprised how easy it was and how well it works (apart from the performance). 

The only thing i could do is not to generate a static body for ereaser strokes..so you can't stand on them. But cutting holes out of strokes seems kind of hard. Possible but hard. Not sure if it's worth it. This is just a silly little easteregg thing anyway :)

**Comment by mbrlabs** [comment]
Alright, so i disabled collision generation for eraser strokes. I also just merged the `player` branch into `main`.

**Comment by Astrono2** [comment]
Have you tested the effect on performance of the collision generation on big drawings with many strokes?

**Comment by mbrlabs** [comment]
@Astrono2 it obviously has an impact on performance, but it's totally fine. In the video below are 1303 strokes with 25595 points and it never drops below 60 FPS (only initially when generating the collision shapes). This is the file: [big.zip](https://github.com/mbrlabs/Lorien/files/6960634/big.zip)


https://user-images.githubusercontent.com/8750135/128845736-8342136b-6579-4525-8a37-ad7d97a2994d.mp4

**Comment by Astrono2** [comment]
Nice
