### ISSUE TITLE
Usage of `signal` name, which is reserved GDScript keyword in Godot 4.0

### ISSUE THREAD

**Issue by qarmin** [mbrlabs/Lorien#57]
https://github.com/mbrlabs/Lorien/blob/56cc6244f68bfa66c41698b1583d90d24ada41d5/lorien/Misc/Utils.gd#L10

I hit on this problem when I tried to run my test script to upgrade project to 4.0

**Comment by mbrlabs** [comment]
What test script are you working on?

`get_signal_connection_list` returns an array with connection dictionaries like this:
````
{binds:[], flags:0, method:_on_project_selected_to_open, signal:file_selected, source:[FileDialog:1710], target:[Panel:1543]}
````
So accessing it like so: `conn["signal"]` should work.

**Comment by qarmin** [comment]
https://github.com/godotengine/godot/pull/51950
For now it is unusable, due to big number of GDScript bugs, which doesn't allow to properly test converted project.

This is how looks converted project
[lorien.zip](https://github.com/mbrlabs/Lorien/files/7111623/lorien.zip)

It spams this errors for now:
```
ERROR: Can't use the compute version of the gaussian blur with the mobile renderer.
   at: gaussian_blur (servers/rendering/renderer_rd/effects_rd.cpp:412)
```
```
SCRIPT ERROR: Parse Error: Could not resolve class "Config", because of a parser error.
          at: GDScript::reload (res://UI/Dialogs/SettingsDialog.gd:39)
```
```
SCRIPT ERROR: Parse Error: Too many arguments for "move_and_slide()" call. Expected at most 0 but received 6.
          at: GDScript::reload (res://Misc/Player/Player.gd:39)
SCRIPT ERROR: Parse Error: Cannot assign a value of type "bool" to a target of type "Vector2".
          at: GDScript::reload (res://Misc/Player/Player.gd:39)
```
```
SCRIPT ERROR: Parse Error: Expected end of statement after return statement, found "," instead.
          at: GDScript::reload (res://BrushStroke/BrushStroke.gd:24)
```
```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload (res://Misc/Config.gd:7)
```

**Comment by mbrlabs** [comment]
Oh, that's cool! I did a manual conversion of Lorien pretty early on in development just to see if it would run. Was not that much work, but for a bigger project automatic conversion could be huge. Especially if the tool is included in the editor. 

I may try this on my other projects in the future if i have time. In the meantime if you want to test annother open source project of mine: https://github.com/mbrlabs/gwj25-tatl. It's a GLES2 3D game i did in Godot 3.2.3 for a jam.
