### ISSUE TITLE
Custom texture as background

### ISSUE THREAD

**Issue by Yianni-Mitropoulos** [mbrlabs/Lorien#73]
It would be nice to be able to choose an image (PNG or JPEG) to use as a 'repeating texture' instead of a background color. This would help people who want a more interesting background texture. Personally, my use case is a bit different. I want to be able to set the background to an image containing a math problem to solve (e.g. it might say "Solve x^2 - 1 = 0"). For my particular use case, it's very important that the image remain un-stretched; I'd like it displayed pixel-by-pixel.

**Comment by mbrlabs** [comment]
I the grid not sufficient for this usecase? TBH i don't really see much use in a customizable background image.
