### ISSUE TITLE
Supereraser

### ISSUE THREAD

**Issue by Yianni-Mitropoulos** [mbrlabs/Lorien#74]
In some whiteboard apps, like on whiteboardfox.com, the eraser is very 'dangerous' and the moment it touches an object the whole object just vanishes. It would be helpful to have a tool like this, either replacing the current eraser or implemented as a separate tool. For the time being, simply using the selection tool and pressing 'delete' is a good option.

**Comment by mbrlabs** [comment]
Sorry, but don't really like this. The normal select-delete workflow works better in my opinion.

**Comment by mbrlabs** [comment]
I'm reopening this, because i changed my mind about it...i actually like the idea/feature now 😁

Not sure though if we should replace the brush-eraser with this new one or add annother one. I'm gravitating towards fully replacing it atm.

**Comment by Th4tGuy69** [comment]
Why not keep the current functionality and switch to the more 'dangerous' mode while holding shift?

**Comment by hansemro** [comment]
Took some time learning enough Godot, but I managed to add super eraser tool as its own tool in my dev branch (https://github.com/hansemro/Lorien/tree/super_eraser_dev). My implementation is not perfect, but I hope it can lead to something better.

To elaborate on some issues with my current implementation:
1) eraser may fail to remove some strokes when moving cursor at high speeds (more noticeable when brush size is small).
2) eraser does not consider stroke's width/size so it may fail to remove stroke even though brush visibly overlaps with it.

**Comment by Yianni-Mitropoulos** [comment]
Here's an idea for a "unified approach": with the draw tool activated, you can left-click to draw a curve. But if you hold SHIFT, instead of drawing a curve, the software selects all objects that your curve intersects with. Press DELETE to delete the selection. With the rectangle tool activated, you can left click to draw a rectangle. But if you hold SHIFT, the software selects all objects that your curve intersects with. Press DELETE to delete the selection. Finally, you can press and hold DELETE to perform "undangerous deletion". If you do this with the freehand tool, it mimics the current behaviour of the eraser. If you do this with the rectangle tool, it deletes the rectangle but leaves pixels outside the rectangle unchanged.

At least, that's how I'd do it.

You'll need to modify my suggestion slightly for tablet user's, since they don't have a keyboard available.

**Comment by mbrlabs** [comment]
@hansemro very cool, this will come in handy. Thanks!

I will probbaly go with @Th4tGuy69's solution and enable it when holding shift while using the eraser.

**Comment by mbrlabs** [comment]
I have implemented a SuperEraser based on @hansemro's implementation. See [this branch](https://github.com/mbrlabs/Lorien/tree/supereraser) (will merge soon)

I also completly removed the old implementation which only painted over and did not really delete strokes. I think this is the right move (instead of keeping both), because this is generally what you want to do in an app like this. It also greatly simplifies the code (the current eraser implementation was pretty hacky).

The savefile format did not change, however previously made eraser-strokes will be skipped when loading .lorien files. Moreover when saving files using the new version, all eraser-strokes will be permanently lost.

**Comment by hansemro** [comment]
@mbrlabs Cool to see, but my implementation does not properly handle various BrushStroke widths. From the perspective of the user, it seems odd that the eraser does not erase a stroke on edge-contact but as it intersects the middle of the stroke. I will try to add a gif demonstrating the issue.

**Comment by mbrlabs** [comment]
I also take that into account using the pressure value of the brush stroke at the intersection point. But it's not perfect yet. See:
https://github.com/mbrlabs/Lorien/blob/3cad26936d0d13c7de2624da1d432a962cd87235/lorien/InfiniteCanvas/Tools/EraserTool.gd#L35-L49

**Comment by hansemro** [comment]
> But it's not perfect yet...i also need to respect the base width of the stroke. See:

This would likely mean replacing Geometry.segment_intersects_circle as we shouldn't assume every brush stroke is a pixel-width line.

Did you have any ideas in mind?

**Comment by mbrlabs** [comment]
Alright, i merged it into the main branch.
Closing this. If there any issues, please open a new issue.
