### ISSUE TITLE
Center view to mouse cursor

### ISSUE THREAD

**Issue by lucasnobre212** [mbrlabs/Lorien#77]
Shortcut to center the view in the mouse cursor, so when we are sketching a diagram or something like it, it is not so troublesome to keep scrolling the view everytime.
Centering it will make the whole task more productive

EDIT: I could try to implement this myself, but I would need some guidance. If you can point me a direction, I would love to help!

**Comment by mbrlabs** [comment]
Implemented in https://github.com/mbrlabs/Lorien/commit/15ab093663946640de6861d7854028e404331287 (not released yet). The shortcut is `C`.
