### ISSUE TITLE
Discussion board?

### ISSUE THREAD

**Issue by fenix-hub** [mbrlabs/Lorien#8]
**Feature/enhancement description:**
Hi, it's me again!

Lately I've been (successfully) using Lorien with my [Huion tablet](https://www.amazon.it/gp/product/B07NY457J4/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) to make some sketches and taking some notes during my engineering study sessions. So thanks again for making this software and letting us contribute.

https://user-images.githubusercontent.com/45271396/120245593-edb1ac00-c26d-11eb-98a8-a58a7817253f.mp4

Would you consider opening a [Discussion section](https://docs.github.com/en/discussions) here on this repo?
I've been using it quite a lot for some of the plugin I'm co-developing [(as this example)](https://github.com/GodotNuts/GodotFirebase/discussions) and I've found it very useful in order to discuss about features and stuff directly with users, without having the necessity to have a discord server, or receiving emails, or using Issues.

I'd like to propose some features, but first I'd like to understend if they are even relevant to your roadmap or not, so having a direct discussion would be helpful. Thanks!

**Comment by mbrlabs** [comment]
Nice, i only tested this on my Wacom so far but Godot's drawing tablet support seems to be solid...i haven't had any bugreports regarding this. Btw, you should update your branch. I rearchitected a lot of stuff and added new features.

Yep, good idea. I actually thought about it but wasn't sure if people were gonna use it since it's a pretty new feature.

**Comment by fenix-hub** [comment]
> Nice, i only tested this on my Wacom so far but Godot's drawing tablet support seems to be solid...i haven't had any bugreports regarding this.

As far as the drawing tablet manufacturer provides the drivers to read the pen as a mouse, and the pressure as analog input, you should be able to support any drawing tablet. But anyway if you need to write specific drivers, it for sure could be done writing some GDNative library for it :)


> Yep, good idea. I actually thought about it but wasn't sure if people were gonna use it since it's a pretty new feature.

Thanks! You can close this if you want

**Comment by mbrlabs** [comment]
Alright, closing then 👍
