### ISSUE TITLE
wish chinese file path support

### ISSUE THREAD

**Issue by nefusmzj** [mbrlabs/Lorien#87]
Now, It not support chinese file path, when save or open white board.  I wish this project can support chinese file path in futher, thank you.

**Comment by mbrlabs** [comment]
Do you mean you can't see files with chinese characters in the file dialog? If so it's probably because the font i'm using does not support Chinese. But it's pretty easy in Godot to change the font based on the locale, so i can add a chinese (maybe also a japanese) font the next release.

**Comment by mbrlabs** [comment]
@LGiki added a chinese font. Maybe this fixed it already. If not then maybe it's a good idea to add an additional mapping from the default fonts to the chinese ones when the application language is Chinese.

Same for Korean (i already added a font for that), but that's annother issue.

**Comment by LGiki** [comment]
I did some tests, when the language is set to a language other than Simplified Chinese, the file paths containing Chinese characters cannot be displayed properly, for example: the `新建文件夹` in `D:\temp\新建文件夹\` will be displayed as blank. But when the language is set to Simplified Chinese, it can be displayed properly. As shown in the following screenshot.

![](https://user-images.githubusercontent.com/20807713/173716124-be0fb2ba-151a-4bdc-8936-808f6ec5e423.png)

I also tested that even if the language is set to a language other than Simplified Chinese (paths containing Chinese characters cannot be displayed properly), Lorien can still open, save and export files to paths containing Chinese characters normally.

So if you want to use Lorien in a path containing Chinese characters, you can set the language to Simplified Chinese and everything will work fine.

**Comment by mbrlabs** [comment]
Great, thanks for testing! I think that's as good as it gets without completly changing all fonts, so i'm closing this as solved.
