### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by therealrobster** [mbrlabs/Lorien#88]
**Feature/enhancement description:**

Hi to the contributors!  First of all, amazing work.  This is an exciting project.  Here are some ideas that might help, I hope you find them useful.

Shortcut keys.

Although they should be programmable, I would recommend copying industry standards.  If I jump into say Aseprite I have the same keys as Photoshop and I can move at ease.  Space and click for grab and pan.  B - Bush.  E - Eraser.  L - Line.  G - Fill paint.   Shift with brush activated should turn into real time line.  Etc.     (aseprite has the easiest to understand if you want to check their system)

Mouse and Navigation.

Mouse wheel should zoom in and out. (already does)

CTRL Mouse wheel should make cursor / brush larger / smaller.

Press and hold Mouse Wheel (button 3) and pan (same as Space and left click to pan)

Zooming in I should be able to continue with smaller and smaller brush sizes.  So I can make use of that infinite zoom type / vector type effect.  I could have a planning chart this way with all the notes in each little square I draw.  Images inside. Text etc.  Smaller and smaller it goes.

Paint issue:

When drawing, if I try and draw a box say, often the corner will 'bend' behind my brush.  IE:  It's not creating a new vector point at the time I move the brush 90 degree.  So I get a box with beveled corners.  It should recognise a hard turn is occurring and add a point at that moment to keep the clarity of the shape.

Other:

Antialiasing is too blurry on the painted lines.  I turn it off and it looks WAY better. Maybe a simple 1 pixel AA or similar?  I'm not sure but it's too much at present.

I hope these points help.  I love your project and am excited to see it happening.

**Comment by mbrlabs** [comment]
Thanks! These are some good suggestions, i will try to add some in the future.

**Comment by mbrlabs** [comment]
I just rememberd this issue. 
I only fixed one issue so far, but IMO it was the most important one on this list:
- Antialiasing is now super sharp on any zoom level and on any hardware. I'm going to release a new version soon.

**Comment by tokazio** [comment]
it can be cool to allow deselect by pointing somewhere far from the selection instead to use the shortcuts or to change the tool.

**Comment by mbrlabs** [comment]
Most of these are implemented now, closing this.
