### ISSUE TITLE
Brush smoothing settings

### ISSUE THREAD

**Issue by voithos** [mbrlabs/Lorien#89]
First off, thanks for the awesome tool!

I really like the simplicity of the current brush tool, but I noticed that it seems to be very sensitive to the perturbations of my pen when I use it with my drawing tablet. It might be useful to add some configurable smoothing options in order to allow smoother strokes. There are several line smoothing algorithms that could work, here's a discussion of a few: https://stackoverflow.com/questions/5829437/efficient-line-smoothing-and-or-simplification.

**Comment by mbrlabs** [comment]
Hello and thanks! Yes, brush smoothing is essential for a good feel and needs to be implemented before 1.0. I did a bit of research myself a couple of months ago and found this Github thread: https://github.com/opentoonz/opentoonz/issues/81.

**Comment by mbrlabs** [comment]
I implemented basic smoothing using cubic Bezier curves: https://github.com/mbrlabs/Lorien/commit/e5e7c26f3953ddc05b0d7a128ec97585978d4508. The strength is adjustable in the settings.
