### ISSUE TITLE
smaller brush sizes lack visablity on higher zooms

### ISSUE THREAD

**Issue by FisherSTA** [mbrlabs/Lorien#90]
there is significant pop out and fading for smaller brush sizes at higher zooms. this is solved by setting opengl hint as the anti aliasing style. I suggest that it is made the default setting.

**Comment by mbrlabs** [comment]
The OpenGL Hint method has unfortuanlly a lot of problems which is why it's not the default:

1) It's just a hint. Graphics drivers can completly ignore this on some machines
2) It's very slow because the lines can't be batched togeher when drawing
