### ISSUE TITLE
User Interface: Zoom In / Out Using Keyboard / Pen

### ISSUE THREAD

**Issue by entity0x** [mbrlabs/Lorien#95]
**Zoom In / Out Using The  Keyboard/Pen**

ALT- Pen already 'pans' across the board, so that is good, but the Zoom needs to be consistent with using the pen and keyboard as well, and could mimic other software interfaces that users are already familiar with and expecting to work the same way.

_Photoshop, Krita, Affinity Designer:_   
Spacebar-Down = Pan image
Ctl - Spacebar + PenDown + Up/Down Movement = Zoom In / Out

Pretty sure this is common for many other applications, with some variation.

Note: I don't consider this an enhancement, but a basic UI interface requirement :D

**Comment by mbrlabs** [comment]
This is already implementd in the main branch (but not available in the latest release). See: https://github.com/mbrlabs/Lorien/pull/71
