### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by seekstar** [mbrlabs/Lorien#96]
**Build instructions:**

I want to check out the latest version, but I have no idea how to build it. ```README``` suggests ```check out the CI builds```, but I can not find any binaries there.

**Comment by mbrlabs** [comment]
You can download the lastest build here (at the bottom under `Artifacts`: https://github.com/mbrlabs/Lorien/actions/runs/1602564010.

If you want to build it yourself you need to download Godot and open `lorien/project.godot` in the editor. It's just a Godot project.

**Comment by seekstar** [comment]
I see. Thank you very much!
