### ISSUE TITLE
Misplaced background colour popup location

### ISSUE THREAD

**Issue by Gurchain** [mbrlabs/Lorien#99]
**Lorien version:**

v0.4.0

**OS/device including version:**

Pop OS 21.10 (Linux)

**Issue description:**

The background colour popup changes location. I think it is because the popup doesn't get clipped.

**Steps to reproduce:**
Resize the window to the minimum size, open the background colour popup. Then, if you open the background colour popup at any other size it will be higher than its supposed to be.

**Comment by mbrlabs** [comment]
Yeah, i can confirm that. Apart from fixing the bug it would probably also a good idea to increase the minimum window size so that the UI won't get squished together when the window is too small.
